import random

# Define the length of the file in characters  
file_length = 100000

# Define the number of characters between each number  
number_interval = 100

# Define the number of characters between each line break
line_break_interval = 4000

# Initialize the file content and character count  
file_content = ""
char_count = 0

# Generate random characters and insert numbers every 100 characters  
for i in range(file_length):
    # Generate a random uppercase letter  
    rand_char = chr(random.randint(65, 90)) if random.random() < 0.5 else chr(random.randint(97, 122))
    # Add the character to the file content  
    file_content += rand_char
    char_count += 1
    number_length = 0
    # Insert a number every 100 characters  
    if char_count % number_interval == 0:
        file_content += "__" + str(char_count) + "__"
        # Increment the character count to account for the added number
        number_length = len(str(char_count)) + 4
        char_count += number_length
    if (char_count - number_length) % line_break_interval == 0:
        file_content += "\n"
        # Increment the character count to account for the added line break
        char_count += 1

# Write the file content to a file  
with open("random_file.txt", "w") as f:
    f.write(file_content)

# This code generates a file of length 10,000 characters (you can change this by modifying the `file_length`
# variable) and inserts a number every 100 characters (you can modify this by changing the `number_interval`
# variable). The file content is generated by randomly selecting uppercase letters and adding them to the file
# content string. The character count is incremented with each added character and the number is inserted every 100
# characters by checking if the character count is divisible by 100. The character count is incremented again to
# account for the added number. Finally, the file content is written to a file named "random_file.txt".
